[package]
name = "toyql"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["cargo", "derive"] }
itertools = "~0.14"
nom = "~8"
rand = "0.9.0"
serde = "1.0.219"
